//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient_Master
    {
        public int IngredientID { get; set; }
        public string IngredientName { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Unit { get; set; }
        public string serving_size { get; set; }
        public Nullable<decimal> calories { get; set; }
        public Nullable<decimal> total_fat { get; set; }
        public Nullable<decimal> cholesterol { get; set; }
        public Nullable<decimal> sodium { get; set; }
        public Nullable<decimal> vitamin_a { get; set; }
        public Nullable<decimal> vitamin_b12 { get; set; }
        public Nullable<decimal> vitamin_b6 { get; set; }
        public Nullable<decimal> vitamin_c { get; set; }
        public Nullable<decimal> vitamin_d { get; set; }
        public Nullable<decimal> vitamin_e { get; set; }
        public Nullable<decimal> vitamin_k { get; set; }
        public Nullable<decimal> calcium { get; set; }
        public Nullable<decimal> iron { get; set; }
        public Nullable<decimal> potassium { get; set; }
        public Nullable<decimal> protein { get; set; }
        public Nullable<decimal> carbohydrate { get; set; }
        public Nullable<decimal> sugars { get; set; }
    }
}
